[package]
name = "page-replacements"
version = "0.1.1"
authors = ["Derrick Lee <dlee3@scu.edu>"]

[dependencies]
fern = { version = "0.5", features = ["colored"] }
log = "0.4"
chrono = "0.4"
clap = "^2.31"
csv = "1.0"
