[package]
name = "page-replacements"
version = "0.1.4"
authors = ["Derrick Lee <dlee3@scu.edu>"]

[dependencies]
chrono = "0.4"
clap = "^2.31"
csv = "1.0"
fern = { version = "0.5", features = ["colored"] }
indicatif = "0.9"
log = "0.4"
parking_lot = "0.5"
threadpool = "1.7"
