[package]
name = "page-replacements"
version = "0.1.0"
authors = ["drklee3 <dlee3@scu.edu>"]

[dependencies]
fern = { version = "0.5", features = ["colored"] }
log = "0.4"
chrono = "0.4"

[features]
default = ["lru"]
fifo = []
lru = []
second_chance = []
